title: "Petch's Dev Journey"
description: "บันทึกการเรียนรู้และผลงานด้านโปรแกรมมิ่งของผม"
twitter_username: your_handle
github_username: kompetch-n
author: PETCH
remote_theme: pages-themes/slate@v0.2.0
show_downloads: false
